### ISSUE TITLE
Key error with related objects

### ISSUE THREAD

**Issue by justb4** [schettino72/sqla_yaml_fixtures#2]
Found in e.g. `test_insert_relation()`.  If the fixture is e.g.:

```
User:
  - __key__: joey
    username: joey
    email: joey@example.com
Profile:
  - user: joey
    name: Jeffrey
```
The function `sqla_yaml_fixtures.load()` will call `data = yaml.load(fixture_text)` where `data` is a `dict` with keys `User` and `Profile`, *but in a dict key/item ordering is random IMO*. If `Profile` is first in the `dict`, the `__key__` `joey` will not be present in the `Store` and give `Key error`.
In Python 3(.6), by chance this may work (is `dict` maybe always `Ordered`?) , but in Python 2 the order is random and usually `Profile`, `User`. 

See https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-compactdict
But also there *The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon*...

**Comment by justb4** [comment]
One way out, and to stay close to the YAML spec is to make Objects a list, e.g.

```
- User:
  - __key__: joey
    username: joey
    email: joey@example.com
- Profile:
  - user: joey
    name: Jeffrey
```

`data` would be a list and order is preserved.
